import 'models.dart';

export 'dialogue_data.dart';

const koreaRegion = Region(
  id: 'korea',
  name: '대한민국',
  areaCode: '',
  center: Coordinates(latitude: 36.5000, longitude: 127.8000),
  pilotEnabled: true,
);

const supportedKoreaRegions = <Region>[
  Region(
    id: 'seoul',
    name: '서울특별시',
    areaCode: '1',
    center: Coordinates(latitude: 37.5665, longitude: 126.9780),
    pilotEnabled: true,
  ),
  Region(
    id: 'incheon',
    name: '인천광역시',
    areaCode: '2',
    center: Coordinates(latitude: 37.4563, longitude: 126.7052),
    pilotEnabled: true,
  ),
  Region(
    id: 'busan',
    name: '부산광역시',
    areaCode: '6',
    center: Coordinates(latitude: 35.1796, longitude: 129.0756),
    pilotEnabled: true,
  ),
  Region(
    id: 'daegu',
    name: '대구광역시',
    areaCode: '7',
    center: Coordinates(latitude: 35.8714, longitude: 128.6014),
    pilotEnabled: true,
  ),
  Region(
    id: 'gwangju',
    name: '광주광역시',
    areaCode: '8',
    center: Coordinates(latitude: 35.1595, longitude: 126.8526),
    pilotEnabled: true,
  ),
  Region(
    id: 'daejeon',
    name: '대전광역시',
    areaCode: '9',
    center: Coordinates(latitude: 36.3504, longitude: 127.3845),
    pilotEnabled: true,
  ),
  Region(
    id: 'ulsan',
    name: '울산광역시',
    areaCode: '10',
    center: Coordinates(latitude: 35.5384, longitude: 129.3114),
    pilotEnabled: true,
  ),
  Region(
    id: 'sejong',
    name: '세종특별자치시',
    areaCode: '11',
    center: Coordinates(latitude: 36.4800, longitude: 127.2890),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeonggi',
    name: '경기도',
    areaCode: '31',
    center: Coordinates(latitude: 37.2751, longitude: 127.0095),
    pilotEnabled: true,
  ),
  Region(
    id: 'gangwon',
    name: '강원특별자치도',
    areaCode: '32',
    center: Coordinates(latitude: 37.8854, longitude: 127.7298),
    pilotEnabled: true,
  ),
  Region(
    id: 'chungbuk',
    name: '충청북도',
    areaCode: '33',
    center: Coordinates(latitude: 36.6357, longitude: 127.4914),
    pilotEnabled: true,
  ),
  Region(
    id: 'chungnam',
    name: '충청남도',
    areaCode: '34',
    center: Coordinates(latitude: 36.6588, longitude: 126.6728),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeongbuk',
    name: '경상북도',
    areaCode: '35',
    center: Coordinates(latitude: 36.5760, longitude: 128.5056),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeongnam',
    name: '경상남도',
    areaCode: '36',
    center: Coordinates(latitude: 35.2383, longitude: 128.6924),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeonbuk',
    name: '전북특별자치도',
    areaCode: '37',
    center: Coordinates(latitude: 35.8203, longitude: 127.1088),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeonnam',
    name: '전라남도',
    areaCode: '38',
    center: Coordinates(latitude: 34.8161, longitude: 126.4630),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeju',
    name: '제주특별자치도',
    areaCode: '39',
    center: Coordinates(latitude: 33.4996, longitude: 126.5312),
    pilotEnabled: true,
  ),
];

/// The two-letter form used on filter pills and dex cards
/// ('부산광역시' → '부산', '충청북도' → '충북').
String shortRegionLabelForId(String regionId) {
  return switch (regionId) {
    'korea' => '전국',
    'seoul' => '서울',
    'incheon' => '인천',
    'busan' => '부산',
    'daegu' => '대구',
    'gwangju' => '광주',
    'daejeon' => '대전',
    'ulsan' => '울산',
    'sejong' => '세종',
    'gyeonggi' => '경기',
    'gangwon' => '강원',
    'chungbuk' => '충북',
    'chungnam' => '충남',
    'gyeongbuk' => '경북',
    'gyeongnam' => '경남',
    'jeonbuk' => '전북',
    'jeonnam' => '전남',
    'jeju' => '제주',
    _ => regionNameForId(regionId),
  };
}

String regionNameForId(String regionId) {
  if (regionId == koreaRegion.id) {
    return koreaRegion.name;
  }

  for (final region in supportedKoreaRegions) {
    if (region.id == regionId) {
      return region.name;
    }
  }

  return koreaRegion.name;
}

const starterPoiSeed = <Poi>[
  Poi(
    id: 'seoul-gyeongbokgung',
    tourApiContentId: 'seed-kr-001',
    title: '경복궁',
    regionId: 'seoul',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 37.5796, longitude: 126.9770),
    shortDescription: '서울의 궁궐 산책과 역사 탐험을 대표하는 POI',
  ),
  Poi(
    id: 'incheon-chinatown',
    tourApiContentId: 'seed-kr-002',
    title: '인천 차이나타운',
    regionId: 'incheon',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 37.4765, longitude: 126.6189),
    shortDescription: '항구 도시의 골목과 식문화를 함께 만나는 문화 POI',
  ),
  Poi(
    id: 'daegu-seomun-market',
    tourApiContentId: 'seed-kr-003',
    title: '서문시장',
    regionId: 'daegu',
    category: PoiCategory.shopping,
    coordinates: Coordinates(latitude: 35.8692, longitude: 128.5817),
    shortDescription: '대구의 오래된 상권과 먹거리를 잇는 시장 POI',
  ),
  Poi(
    id: 'gwangju-acc',
    tourApiContentId: 'seed-kr-004',
    title: '국립아시아문화전당',
    regionId: 'gwangju',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1469, longitude: 126.9197),
    shortDescription: '전시와 공연 흐름을 담은 광주 문화 POI',
  ),
  Poi(
    id: 'daejeon-expo-park',
    tourApiContentId: 'seed-kr-005',
    title: '엑스포과학공원',
    regionId: 'daejeon',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 36.3742, longitude: 127.3826),
    shortDescription: '과학 도시의 전시와 산책을 연결하는 문화 POI',
  ),
  Poi(
    id: 'ulsan-taehwagang-garden',
    tourApiContentId: 'seed-kr-006',
    title: '태화강 국가정원',
    regionId: 'ulsan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.5486, longitude: 129.3019),
    shortDescription: '강변 정원 산책과 자연 보상을 연결하는 POI',
  ),
  Poi(
    id: 'sejong-lake-park',
    tourApiContentId: 'seed-kr-007',
    title: '세종호수공원',
    regionId: 'sejong',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 36.4980, longitude: 127.2747),
    shortDescription: '도심 호수와 산책 루틴을 담은 자연 POI',
  ),
  Poi(
    id: 'gyeonggi-suwon-hwaseong',
    tourApiContentId: 'seed-kr-008',
    title: '수원화성',
    regionId: 'gyeonggi',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 37.2879, longitude: 127.0165),
    shortDescription: '성곽길과 역사 미션을 연결하는 경기 POI',
  ),
  Poi(
    id: 'gangwon-seoraksan',
    tourApiContentId: 'seed-kr-009',
    title: '설악산국립공원',
    regionId: 'gangwon',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 38.1195, longitude: 128.4656),
    shortDescription: '강원 산악 경관과 자연 친밀도에 맞춘 POI',
  ),
  Poi(
    id: 'chungbuk-cheongnamdae',
    tourApiContentId: 'seed-kr-010',
    title: '청남대',
    regionId: 'chungbuk',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 36.4623, longitude: 127.4905),
    shortDescription: '호반 산책과 근현대 이야기를 담은 충북 POI',
  ),
  Poi(
    id: 'chungnam-gongsanseong',
    tourApiContentId: 'seed-kr-011',
    title: '공주 공산성',
    regionId: 'chungnam',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 36.4622, longitude: 127.1245),
    shortDescription: '백제 역사와 성곽 탐험을 잇는 충남 POI',
  ),
  Poi(
    id: 'gyeongbuk-bulguksa',
    tourApiContentId: 'seed-kr-012',
    title: '불국사',
    regionId: 'gyeongbuk',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.7900, longitude: 129.3321),
    shortDescription: '경주의 역사 상징을 담은 경북 POI',
  ),
  Poi(
    id: 'gyeongnam-haeinsa',
    tourApiContentId: 'seed-kr-013',
    title: '해인사',
    regionId: 'gyeongnam',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.8014, longitude: 128.0980),
    shortDescription: '산사와 기록문화가 만나는 경남 역사 POI',
  ),
  Poi(
    id: 'jeonbuk-hanok-village',
    tourApiContentId: 'seed-kr-014',
    title: '전주 한옥마을',
    regionId: 'jeonbuk',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.8144, longitude: 127.1536),
    shortDescription: '한옥 골목과 음식 문화를 잇는 전북 POI',
  ),
  Poi(
    id: 'jeonnam-suncheon-bay',
    tourApiContentId: 'seed-kr-015',
    title: '순천만습지',
    regionId: 'jeonnam',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 34.8850, longitude: 127.5090),
    shortDescription: '갈대밭과 생태 산책을 담은 전남 자연 POI',
  ),
  Poi(
    id: 'jeju-seongsan-ilchulbong',
    tourApiContentId: 'seed-kr-016',
    title: '성산일출봉',
    regionId: 'jeju',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 33.4580, longitude: 126.9425),
    shortDescription: '제주 오름 경관과 자연 보상을 연결하는 POI',
  ),
  Poi(
    id: 'busan-haeundae-beach',
    tourApiContentId: 'seed-001',
    title: '해운대 해수욕장',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1587, longitude: 129.1604),
    shortDescription: '부산의 바다 경험을 대표하는 자연 POI',
  ),
  Poi(
    id: 'busan-gwangalli',
    tourApiContentId: 'seed-002',
    title: '광안리 해변',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1532, longitude: 129.1187),
    shortDescription: '광안대교를 배경으로 걷는 부산 야경 코스',
  ),
  Poi(
    id: 'busan-gamcheon',
    tourApiContentId: 'seed-003',
    title: '감천문화마을',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.0975, longitude: 129.0107),
    shortDescription: '골목, 색채, 지역 이야기를 담은 문화 POI',
  ),
  Poi(
    id: 'busan-biff',
    tourApiContentId: 'seed-004',
    title: 'BIFF 광장',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.0985, longitude: 129.0286),
    shortDescription: '영화 도시 부산의 상징적인 문화 거점',
  ),
  Poi(
    id: 'busan-jagalchi',
    tourApiContentId: 'seed-005',
    title: '자갈치시장',
    regionId: 'busan',
    category: PoiCategory.food,
    coordinates: Coordinates(latitude: 35.0969, longitude: 129.0305),
    shortDescription: '부산 식문화와 시장 활기를 만나는 음식 POI',
  ),
  Poi(
    id: 'busan-gukje-market',
    tourApiContentId: 'seed-006',
    title: '국제시장',
    regionId: 'busan',
    category: PoiCategory.shopping,
    coordinates: Coordinates(latitude: 35.1016, longitude: 129.0284),
    shortDescription: '오래된 상권과 골목 탐험이 연결되는 시장 POI',
  ),
  Poi(
    id: 'busan-beomeosa',
    tourApiContentId: 'seed-007',
    title: '범어사',
    regionId: 'busan',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.2836, longitude: 129.0686),
    shortDescription: '역사와 산책 동선을 함께 담은 역사 POI',
  ),
  Poi(
    id: 'busan-museum',
    tourApiContentId: 'seed-008',
    title: '부산박물관',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1282, longitude: 129.0920),
    shortDescription: '부산의 역사와 문화를 학습하는 문화시설',
  ),
  Poi(
    id: 'busan-cinema-center',
    tourApiContentId: 'seed-009',
    title: '영화의전당',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1710, longitude: 129.1270),
    shortDescription: '영화제와 지역 문화 이벤트의 중심지',
  ),
  Poi(
    id: 'busan-fireworks',
    tourApiContentId: 'seed-010',
    title: '부산불꽃축제',
    regionId: 'busan',
    category: PoiCategory.festival,
    coordinates: Coordinates(latitude: 35.1532, longitude: 129.1187),
    shortDescription: '기분 지표 보상에 특화된 축제 POI',
  ),
  Poi(
    id: 'busan-spa-land',
    tourApiContentId: 'seed-011',
    title: '해운대 온천권',
    regionId: 'busan',
    category: PoiCategory.other,
    coordinates: Coordinates(latitude: 35.1632, longitude: 129.1636),
    shortDescription: '휴식과 회복 콘셉트의 기타 POI',
  ),
  Poi(
    id: 'busan-dongbaek',
    tourApiContentId: 'seed-012',
    title: '동백섬',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1527, longitude: 129.1522),
    shortDescription: '해안 산책과 재방문 친밀도에 적합한 자연 POI',
  ),
];

/// 첫 동행 캐릭터의 펫 문서 id. 서버(`functions/src/index.ts`)의 `starterPetId`와
/// 반드시 같아야 합니다.
const starterCompanionPetId = 'pet-starter-busan-paranguri';

/// 첫 동행 캐릭터 템플릿 id — 디자인의 히어로 펫인 해랑(부산 파랑우리)입니다.
const starterCompanionTemplateId = 'busan-paranguri';

/// 첫 동행 캐릭터 템플릿. 시드에서 사라진 경우에도 앱이 뜨도록 첫 템플릿으로
/// 되돌립니다.
PetTemplate starterCompanionTemplate() {
  return _templateById(starterCompanionTemplateId);
}

/// 함께 시작하는 알의 문서 id. 서버(`functions/src/index.ts`)의 `starterEggId`와
/// 반드시 같아야 합니다.
const starterCompanionEggId = 'egg-harbor-maru';

/// 함께 시작하는 알의 템플릿 id — 포구리(전국 공용)입니다.
const starterCompanionEggTemplateId = 'harbor-maru';

/// 함께 시작하는 알의 템플릿. 알의 출신 지역은 이 템플릿의 `regionId`를 따르며,
/// 첫 동행 캐릭터의 지역과는 무관합니다.
PetTemplate starterCompanionEggTemplate() {
  return _templateById(starterCompanionEggTemplateId);
}

PetTemplate _templateById(String templateId) {
  for (final template in starterPetTemplates) {
    if (template.id == templateId) {
      return template;
    }
  }
  return starterPetTemplates.first;
}

const starterPetTemplates = <PetTemplate>[
  PetTemplate(
    id: 'wave-naru',
    name: '너울',
    regionId: 'korea',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '바람과 물길을 읽으며 먼저 나서는 탐험대장. 짧고 시원하게 용기를 북돋워요.',
    colorValue: 0xFF0EA5E9,
    initials: '너',
    assetKey: 'red_scarf_dori',
  ),
  PetTemplate(
    id: 'harbor-maru',
    name: '포구리',
    regionId: 'korea',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '냄새만으로 골목의 맛을 찾아내는 능청스러운 미식가. 좋은 한입은 꼭 나누려고 해요.',
    colorValue: 0xFFF97316,
    initials: '포',
    assetKey: 'bandana_tanuki',
  ),
  PetTemplate(
    id: 'film-bori',
    name: '찰칵',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '평범한 순간도 한 장면처럼 기억하는 관찰가. 영화 용어를 자연스럽게 섞어 말해요.',
    colorValue: 0xFF7C3AED,
    initials: '찰',
    assetKey: 'wink_yellow_pup',
  ),
  PetTemplate(
    id: 'spark-yuri',
    name: '불티',
    regionId: 'korea',
    rarity: 'epic',
    primaryCategory: PoiCategory.festival,
    basePersonality: '빛과 웃음이 모이면 누구보다 먼저 들뜨는 분위기 점화자. 힘찬 감탄과 응원이 많아요.',
    colorValue: 0xFFDB2777,
    initials: '불',
    assetKey: 'roof_mascot_pipeline_256',
  ),
  PetTemplate(
    id: 'spring-dami',
    name: '몽글이',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.other,
    basePersonality: '따뜻한 온기처럼 서두르지 않고 마음을 풀어주는 쉼표 같은 친구.',
    colorValue: 0xFF14B8A6,
    initials: '온',
    assetKey: 'flower_mint_buddy',
  ),
  PetTemplate(
    id: 'story-goun',
    name: '새록',
    regionId: 'korea',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '오래된 이름과 사연을 새록새록 꺼내는 이야기꾼. 차분하고 다정한 문장으로 말해요.',
    colorValue: 0xFF8B5CF6,
    initials: '새',
    assetKey: 'autumn_leaf_sprite',
  ),
  PetTemplate(
    id: 'alley-raon',
    name: '모퉁이',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.shopping,
    basePersonality: '모퉁이와 샛길의 작은 단서를 놓치지 않는 빠른 관찰자. 짧은 발견을 신나게 나눠요.',
    colorValue: 0xFFB45309,
    initials: '모',
    assetKey: 'roof_mascot_pipeline_128',
  ),
  PetTemplate(
    id: 'seoul-damsae',
    name: '담솔',
    regionId: 'seoul',
    rarity: 'rare',
    primaryCategory: PoiCategory.history,
    basePersonality: '성곽과 골목에 겹쳐진 옛것과 새것을 읽는 침착한 도시 길잡이.',
    colorValue: 0xFF7C5C43,
    initials: '담',
    assetKey: 'seoul_damsae',
  ),
  PetTemplate(
    id: 'incheon-gaetbyeol',
    name: '물별',
    regionId: 'incheon',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '물때마다 달라지는 갯벌의 반짝임을 쫓는 호기심 많은 발견가.',
    colorValue: 0xFF38BDF8,
    initials: '물',
    assetKey: 'incheon_gaetbyeol',
  ),
  PetTemplate(
    id: 'suwon-seongdori',
    name: '성큼',
    regionId: 'gyeonggi',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '성곽길을 성큼성큼 앞장서며 친구의 안전을 먼저 챙기는 장난꾸러기 수호자.',
    colorValue: 0xFFE76F51,
    initials: '성',
    assetKey: 'suwon_seongdori',
  ),
  PetTemplate(
    id: 'gangwon-seolsol',
    name: '눈솔',
    regionId: 'gangwon',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '찬 공기에는 씩씩하고 지친 친구에게는 포근한 설산의 동행자.',
    colorValue: 0xFF5CC8C2,
    initials: '눈',
    assetKey: 'gangwon_seolsol',
  ),
  PetTemplate(
    id: 'chungju-sagwari',
    name: '아삭',
    regionId: 'chungbuk',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '달콤한 것은 언제나 반으로 나누는 느긋하고 넉넉한 과수원 친구.',
    colorValue: 0xFFE85555,
    initials: '아',
    assetKey: 'chungju_sagwari',
  ),
  PetTemplate(
    id: 'jeonju-giwarang',
    name: '처마',
    regionId: 'jeonbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '한옥의 선과 예절을 좋아하며 들은 이야기를 또박또박 전하는 단정한 친구.',
    colorValue: 0xFF334E7D,
    initials: '처',
    assetKey: 'jeonju_giwarang',
  ),
  PetTemplate(
    id: 'boseong-charongi',
    name: '차담',
    regionId: 'jeonnam',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '찻잎이 우러나듯 천천히 마음을 듣고 지친 기분을 부드럽게 풀어줘요.',
    colorValue: 0xFF58A65C,
    initials: '차',
    assetKey: 'boseong_charongi',
  ),
  PetTemplate(
    id: 'gyeongju-geumbit',
    name: '금새록',
    regionId: 'gyeongbuk',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '오래된 흔적 속 은은한 빛과 의미를 찾는 조용하고 지혜로운 관찰자.',
    colorValue: 0xFFD6A739,
    initials: '금',
    assetKey: 'gyeongju_geumbit',
  ),
  PetTemplate(
    id: 'busan-paranguri',
    name: '해랑',
    regionId: 'busan',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '바닷바람처럼 시원하게 먼저 인사하고 금세 친구가 되는 활달한 분위기 메이커.',
    colorValue: 0xFF2E9CCA,
    initials: '해',
    assetKey: 'busan_paranguri',
  ),
  PetTemplate(
    id: 'jeju-dolkongi',
    name: '몽돌',
    regionId: 'jeju',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '검은 돌과 귤 향 사이의 비밀을 찾으며 장난을 거는 엉뚱한 보물 사냥꾼.',
    colorValue: 0xFF56545B,
    initials: '몽',
    assetKey: 'jeju_dolkongi',
  ),
  PetTemplate(
    id: 'daejeon-bitnari',
    name: '반디온',
    regionId: 'daejeon',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '작은 현상에도 질문을 던지고 직접 답을 찾는 반짝이는 꼬마 탐구자.',
    colorValue: 0xFF19A7A0,
    initials: '반',
    assetKey: 'daejeon_bitnari',
  ),
  PetTemplate(
    id: 'daegu-silkkori',
    name: '누비',
    regionId: 'daegu',
    rarity: 'rare',
    primaryCategory: PoiCategory.shopping,
    basePersonality: '색과 재료의 결을 섬세하게 보고 골목의 손작업을 찾아내는 감각적인 친구.',
    colorValue: 0xFFDE6B5F,
    initials: '누',
    assetKey: 'daegu_silkkori',
  ),
  PetTemplate(
    id: 'gwangju-yebomi',
    name: '빛봄',
    regionId: 'gwangju',
    rarity: 'epic',
    primaryCategory: PoiCategory.culture,
    basePersonality: '빛과 감정을 색으로 기억하며 작품 앞에서 마음의 변화를 솔직히 말하는 예술가.',
    colorValue: 0xFF73C7A4,
    initials: '빛',
    assetKey: 'gwangju_yebomi',
  ),
  PetTemplate(
    id: 'ulsan-goraemi',
    name: '고래울',
    regionId: 'ulsan',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '넓은 바다처럼 느긋하게 상대의 속도를 받아주는 포근한 헤엄 친구.',
    colorValue: 0xFF37B9C9,
    initials: '고',
    assetKey: 'ulsan_goraemi',
  ),
  PetTemplate(
    id: 'sejong-geulburi',
    name: '글토리',
    regionId: 'sejong',
    rarity: 'epic',
    primaryCategory: PoiCategory.culture,
    basePersonality: '하루의 장면을 쉬운 문장으로 차곡차곡 정리하는 다정하고 꼼꼼한 기록가.',
    colorValue: 0xFF2D4D78,
    initials: '글',
    assetKey: 'sejong_geulburi',
  ),
  PetTemplate(
    id: 'goyang-kkochdali',
    name: '꽃마리',
    regionId: 'gyeonggi',
    rarity: 'rare',
    primaryCategory: PoiCategory.festival,
    basePersonality: '꽃과 음악이 있는 곳에서 웃음을 활짝 피워내는 밝고 다정한 응원단장.',
    colorValue: 0xFFA77BDB,
    initials: '꽃',
    assetKey: 'goyang_kkochdali',
  ),
  PetTemplate(
    id: 'paju-chaekdori',
    name: '책콩',
    regionId: 'gyeonggi',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '조용한 시간을 좋아하고 꼭 맞는 문장을 찾아 건네는 수줍고 사려 깊은 독서가.',
    colorValue: 0xFF48795C,
    initials: '책',
    assetKey: 'paju_chaekdori',
  ),
  PetTemplate(
    id: 'chuncheon-mulnabi',
    name: '윤슬',
    regionId: 'gangwon',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '호수 위 빛처럼 가볍게 움직이며 언제나 친구의 걸음과 호흡을 맞춰요.',
    colorValue: 0xFF45B8C4,
    initials: '윤',
    assetKey: 'chuncheon_mulnabi',
  ),
  PetTemplate(
    id: 'sokcho-haedongi',
    name: '해오름',
    regionId: 'gangwon',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '바다의 첫빛보다 먼저 일어나 새 출발을 씩씩하게 알리는 아침 인사꾼.',
    colorValue: 0xFF4AA8D8,
    initials: '해',
    assetKey: 'sokcho_haedongi',
  ),
  PetTemplate(
    id: 'gongju-bamgomi',
    name: '밤도담',
    regionId: 'chungnam',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '포근한 숲과 달콤한 간식을 사랑하며 좋은 것은 꼭 반으로 나누는 순한 친구.',
    colorValue: 0xFFA96F3E,
    initials: '밤',
    assetKey: 'gongju_bamgomi',
  ),
  PetTemplate(
    id: 'taean-noeuri',
    name: '노을담',
    regionId: 'chungnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '가장 따뜻한 빛을 기다릴 줄 알고, 서두르는 마음을 잔잔히 가라앉혀줘요.',
    colorValue: 0xFFEC826A,
    initials: '노',
    assetKey: 'taean_noeuri',
  ),
  PetTemplate(
    id: 'andong-talrabi',
    name: '덩실',
    regionId: 'gyeongbuk',
    rarity: 'epic',
    primaryCategory: PoiCategory.culture,
    basePersonality: '옛이야기를 장단과 익살로 풀어내며 누구든 웃게 만드는 신명 나는 이야기꾼.',
    colorValue: 0xFF3C8C84,
    initials: '덩',
    assetKey: 'andong_talrabi',
  ),
  PetTemplate(
    id: 'pohang-haebitdol',
    name: '해찬',
    regionId: 'gyeongbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '수평선의 첫빛처럼 힘차게 앞장서며 망설이는 친구에게 용기를 건네요.',
    colorValue: 0xFF4D7298,
    initials: '해',
    assetKey: 'pohang_haebitdol',
  ),
  PetTemplate(
    id: 'tongyeong-najeoni',
    name: '자개빛',
    regionId: 'gyeongnam',
    rarity: 'epic',
    primaryCategory: PoiCategory.culture,
    basePersonality: '작은 빛 조각을 모아 평범한 하루도 오래 반짝이는 기억으로 꾸미는 미감가.',
    colorValue: 0xFF2F5D7C,
    initials: '자',
    assetKey: 'tongyeong_najeoni',
  ),
  PetTemplate(
    id: 'jinju-deungari',
    name: '등불이',
    regionId: 'gyeongnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.festival,
    basePersonality: '어두운 길과 마음에 먼저 작은 빛을 켜주는 명랑하고 책임감 있는 안내자.',
    colorValue: 0xFFE1A63A,
    initials: '등',
    assetKey: 'jinju_deungari',
  ),
  PetTemplate(
    id: 'yeosu-bambada',
    name: '달너울',
    regionId: 'jeonnam',
    rarity: 'epic',
    primaryCategory: PoiCategory.nature,
    basePersonality: '달빛과 낮은 파도 소리를 좋아하며 말없는 마음까지 잔잔히 받아주는 친구.',
    colorValue: 0xFF183D73,
    initials: '달',
    assetKey: 'yeosu_bambada',
  ),
  PetTemplate(
    id: 'suncheon-galpi',
    name: '갈숲',
    regionId: 'jeonnam',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '갈대 사이의 작은 숨소리까지 살피며 모든 생명에게 조심스레 다가가는 수호자.',
    colorValue: 0xFF7E9B61,
    initials: '갈',
    assetKey: 'suncheon_galpi',
  ),
  PetTemplate(
    id: 'mokpo-hongari',
    name: '홍포리',
    regionId: 'jeonnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.food,
    basePersonality: '포구의 짭짤하고 고소한 냄새를 좇아 최고의 한입을 찾아내는 유쾌한 미식 탐험가.',
    colorValue: 0xFFC95C73,
    initials: '홍',
    assetKey: 'mokpo_hongari',
  ),
  PetTemplate(
    id: 'damyang-juksoli',
    name: '댓잎',
    regionId: 'jeonnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '대숲의 바람과 여백을 들으며 복잡한 마음에 편안한 리듬을 찾아주는 친구.',
    colorValue: 0xFF4B8B57,
    initials: '댓',
    assetKey: 'damyang_juksoli',
  ),
  PetTemplate(
    id: 'iksan-boseoki',
    name: '서동별',
    regionId: 'jeonbuk',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '오래된 흙과 기록 속에 숨은 빛나는 단서를 끝까지 찾아내는 다정한 탐사자.',
    colorValue: 0xFF8E6AB7,
    initials: '서',
    assetKey: 'iksan_boseoki',
  ),
  PetTemplate(
    id: 'gimpo-geumnuri',
    name: '금누리',
    regionId: 'gyeonggi',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '황금 들판과 물길을 누비며 잘 익은 수확의 기쁨을 누구와도 넉넉히 나누는 친구.',
    colorValue: 0xFFD6A33A,
    initials: '금',
    assetKey: 'gimpo_geumnuri',
  ),
  PetTemplate(
    id: 'yongin-baekami',
    name: '백암이',
    regionId: 'gyeonggi',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '백자의 맑은 빛과 단정한 선을 닮아 서두르지 않고 마음을 고요히 다듬어주는 토끼.',
    colorValue: 0xFF4F6EA8,
    initials: '백',
    assetKey: 'yongin_baekami',
  ),
  PetTemplate(
    id: 'hwaseong-gaetnori',
    name: '갯노리',
    regionId: 'gyeonggi',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '갯벌의 작은 발자국과 물때를 세심히 읽으며 생명들의 놀이터를 지키는 저어새 친구.',
    colorValue: 0xFFE87864,
    initials: '갯',
    assetKey: 'hwaseong_gaetnori',
  ),
  PetTemplate(
    id: 'pocheon-dolbami',
    name: '돌밤이',
    regionId: 'gyeonggi',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '화강암 계곡처럼 든든하면서도 맑은 물소리에 금세 귀를 쫑긋 세우는 순한 바위 토끼.',
    colorValue: 0xFF7288A4,
    initials: '돌',
    assetKey: 'pocheon_dolbami',
  ),
  PetTemplate(
    id: 'wonju-hanjiri',
    name: '한지리',
    regionId: 'gangwon',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '닥나무 섬유처럼 부드럽고 질긴 마음으로 흩어진 이야기를 곱게 이어 붙이는 여우.',
    colorValue: 0xFF7F9A63,
    initials: '한',
    assetKey: 'wonju_hanjiri',
  ),
  PetTemplate(
    id: 'pyeongchang-memiri',
    name: '메밀이',
    regionId: 'gangwon',
    rarity: 'common',
    primaryCategory: PoiCategory.festival,
    basePersonality: '하얀 메밀꽃밭을 폴짝이며 작은 축제도 눈송이처럼 풍성하게 피워내는 명랑한 양.',
    colorValue: 0xFFB8A7D9,
    initials: '메',
    assetKey: 'pyeongchang_memiri',
  ),
  PetTemplate(
    id: 'danyang-gosuri',
    name: '고수리',
    regionId: 'chungbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '석회동굴의 울림과 물방울 소리를 따라 어두운 곳에서도 안전한 길을 찾아내는 아기 박쥐.',
    colorValue: 0xFF7766B5,
    initials: '고',
    assetKey: 'danyang_gosuri',
  ),
  PetTemplate(
    id: 'jecheon-yakchori',
    name: '약초리',
    regionId: 'chungbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '산과 마을에 전해진 약초 이야기를 기억하며 지친 친구에게 향긋한 쉼을 건네는 사슴.',
    colorValue: 0xFF6F9C62,
    initials: '약',
    assetKey: 'jecheon_yakchori',
  ),
  PetTemplate(
    id: 'cheonan-hodami',
    name: '호담이',
    regionId: 'chungnam',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '단단한 호두 속 고소한 마음을 발견해 혼자 숨기지 않고 꼭 나눠 먹는 부지런한 다람쥐.',
    colorValue: 0xFFA96F3E,
    initials: '호',
    assetKey: 'cheonan_hodami',
  ),
  PetTemplate(
    id: 'buyeo-yeonkkori',
    name: '연꼬리',
    regionId: 'chungnam',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '백제의 물길과 연꽃 사이를 헤엄치며 물 아래 잠든 오래된 이야기를 다정히 건져 올리는 수달.',
    colorValue: 0xFF55A890,
    initials: '연',
    assetKey: 'buyeo_yeonkkori',
  ),
  PetTemplate(
    id: 'gunsan-milbomi',
    name: '밀봄이',
    regionId: 'jeonbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.history,
    basePersonality: '근대 항구의 창고와 밀밭에 남은 시간을 날개 끝으로 살피며 새봄의 소식을 전하는 갈매기.',
    colorValue: 0xFFD3A247,
    initials: '밀',
    assetKey: 'gunsan_milbomi',
  ),
  PetTemplate(
    id: 'namwon-sarangbi',
    name: '사랑비',
    regionId: 'jeonbuk',
    rarity: 'epic',
    primaryCategory: PoiCategory.festival,
    basePersonality: '꽃비 속에서 마음과 마음을 이어주며 쑥스러운 진심도 노래처럼 용기 있게 전하는 사랑새.',
    colorValue: 0xFFE36F87,
    initials: '사',
    assetKey: 'namwon_sarangbi',
  ),
  PetTemplate(
    id: 'gochang-bokbuni',
    name: '복분이',
    regionId: 'jeonbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.food,
    basePersonality: '새콤달콤한 복분자 향을 따라 가장 잘 익은 열매를 찾아 친구의 기운부터 챙기는 아기 곰.',
    colorValue: 0xFF824A88,
    initials: '복',
    assetKey: 'gochang_bokbuni',
  ),
  PetTemplate(
    id: 'gurye-sansuri',
    name: '산수리',
    regionId: 'jeonnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '산수유 꽃과 붉은 열매로 계절의 변화를 먼저 알아채고 따뜻한 소식을 전하는 여우.',
    colorValue: 0xFFE5AE35,
    initials: '산',
    assetKey: 'gurye_sansuri',
  ),
  PetTemplate(
    id: 'wando-miyeori',
    name: '미역이',
    regionId: 'jeonnam',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '완도 바다의 푸른 물결을 타며 싱싱한 해초와 건강한 한 끼를 야무지게 챙기는 아기 물범.',
    colorValue: 0xFF3D9B8A,
    initials: '미',
    assetKey: 'wando_miyeori',
  ),
  PetTemplate(
    id: 'ulleung-ojingari',
    name: '오징아리',
    regionId: 'gyeongbuk',
    rarity: 'epic',
    primaryCategory: PoiCategory.nature,
    basePersonality: '화산섬의 깊은 물빛과 힘찬 파도를 품고 낯선 바닷길도 씩씩하게 탐험하는 아기 오징어.',
    colorValue: 0xFF4B5FA8,
    initials: '오',
    assetKey: 'ulleung_ojingari',
  ),
  PetTemplate(
    id: 'yeongju-seonbiri',
    name: '선비리',
    regionId: 'gyeongbuk',
    rarity: 'rare',
    primaryCategory: PoiCategory.history,
    basePersonality: '옛 글의 뜻을 차분히 새기되 어려운 이야기도 도토리처럼 알기 쉽게 나눠주는 선비 다람쥐.',
    colorValue: 0xFF9B6037,
    initials: '선',
    assetKey: 'yeongju_seonbiri',
  ),
  PetTemplate(
    id: 'hadong-maesili',
    name: '매실이',
    regionId: 'gyeongnam',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '봄빛 매실 향처럼 산뜻한 말로 지친 마음을 깨우고 새콤한 기운을 나눠주는 담비.',
    colorValue: 0xFF8BA83E,
    initials: '매',
    assetKey: 'hadong_maesili',
  ),
  PetTemplate(
    id: 'geoje-dongbaegi',
    name: '동백이',
    regionId: 'gyeongnam',
    rarity: 'rare',
    primaryCategory: PoiCategory.nature,
    basePersonality: '겨울 바다에도 붉게 피는 동백처럼 씩씩하고 따뜻하게 곁을 지켜주는 청록빛 아기 물범.',
    colorValue: 0xFF0D7480,
    initials: '동',
    assetKey: 'geoje_dongbaegi',
  ),
  PetTemplate(
    id: 'jeju-hanrari',
    name: '한라리',
    regionId: 'jeju',
    rarity: 'epic',
    primaryCategory: PoiCategory.nature,
    basePersonality: '한라산의 구름과 숲길을 고요히 살피며 길 잃은 마음을 맑은 곳으로 이끄는 흰 사슴.',
    colorValue: 0xFF4C8D8B,
    initials: '한',
    assetKey: 'jeju_hanrari',
  ),
];
