import 'models.dart';

const koreaRegion = Region(
  id: 'korea',
  name: '대한민국',
  areaCode: '',
  center: Coordinates(latitude: 36.5000, longitude: 127.8000),
  pilotEnabled: true,
);

const supportedKoreaRegions = <Region>[
  Region(
    id: 'seoul',
    name: '서울특별시',
    areaCode: '1',
    center: Coordinates(latitude: 37.5665, longitude: 126.9780),
    pilotEnabled: true,
  ),
  Region(
    id: 'incheon',
    name: '인천광역시',
    areaCode: '2',
    center: Coordinates(latitude: 37.4563, longitude: 126.7052),
    pilotEnabled: true,
  ),
  Region(
    id: 'busan',
    name: '부산광역시',
    areaCode: '6',
    center: Coordinates(latitude: 35.1796, longitude: 129.0756),
    pilotEnabled: true,
  ),
  Region(
    id: 'daegu',
    name: '대구광역시',
    areaCode: '7',
    center: Coordinates(latitude: 35.8714, longitude: 128.6014),
    pilotEnabled: true,
  ),
  Region(
    id: 'gwangju',
    name: '광주광역시',
    areaCode: '8',
    center: Coordinates(latitude: 35.1595, longitude: 126.8526),
    pilotEnabled: true,
  ),
  Region(
    id: 'daejeon',
    name: '대전광역시',
    areaCode: '9',
    center: Coordinates(latitude: 36.3504, longitude: 127.3845),
    pilotEnabled: true,
  ),
  Region(
    id: 'ulsan',
    name: '울산광역시',
    areaCode: '10',
    center: Coordinates(latitude: 35.5384, longitude: 129.3114),
    pilotEnabled: true,
  ),
  Region(
    id: 'sejong',
    name: '세종특별자치시',
    areaCode: '11',
    center: Coordinates(latitude: 36.4800, longitude: 127.2890),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeonggi',
    name: '경기도',
    areaCode: '31',
    center: Coordinates(latitude: 37.2751, longitude: 127.0095),
    pilotEnabled: true,
  ),
  Region(
    id: 'gangwon',
    name: '강원특별자치도',
    areaCode: '32',
    center: Coordinates(latitude: 37.8854, longitude: 127.7298),
    pilotEnabled: true,
  ),
  Region(
    id: 'chungbuk',
    name: '충청북도',
    areaCode: '33',
    center: Coordinates(latitude: 36.6357, longitude: 127.4914),
    pilotEnabled: true,
  ),
  Region(
    id: 'chungnam',
    name: '충청남도',
    areaCode: '34',
    center: Coordinates(latitude: 36.6588, longitude: 126.6728),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeongbuk',
    name: '경상북도',
    areaCode: '35',
    center: Coordinates(latitude: 36.5760, longitude: 128.5056),
    pilotEnabled: true,
  ),
  Region(
    id: 'gyeongnam',
    name: '경상남도',
    areaCode: '36',
    center: Coordinates(latitude: 35.2383, longitude: 128.6924),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeonbuk',
    name: '전북특별자치도',
    areaCode: '37',
    center: Coordinates(latitude: 35.8203, longitude: 127.1088),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeonnam',
    name: '전라남도',
    areaCode: '38',
    center: Coordinates(latitude: 34.8161, longitude: 126.4630),
    pilotEnabled: true,
  ),
  Region(
    id: 'jeju',
    name: '제주특별자치도',
    areaCode: '39',
    center: Coordinates(latitude: 33.4996, longitude: 126.5312),
    pilotEnabled: true,
  ),
];

String regionNameForId(String regionId) {
  if (regionId == koreaRegion.id) {
    return koreaRegion.name;
  }

  for (final region in supportedKoreaRegions) {
    if (region.id == regionId) {
      return region.name;
    }
  }

  return koreaRegion.name;
}

const starterPoiSeed = <Poi>[
  Poi(
    id: 'seoul-gyeongbokgung',
    tourApiContentId: 'seed-kr-001',
    title: '경복궁',
    regionId: 'seoul',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 37.5796, longitude: 126.9770),
    shortDescription: '서울의 궁궐 산책과 역사 탐험을 대표하는 POI',
  ),
  Poi(
    id: 'incheon-chinatown',
    tourApiContentId: 'seed-kr-002',
    title: '인천 차이나타운',
    regionId: 'incheon',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 37.4765, longitude: 126.6189),
    shortDescription: '항구 도시의 골목과 식문화를 함께 만나는 문화 POI',
  ),
  Poi(
    id: 'daegu-seomun-market',
    tourApiContentId: 'seed-kr-003',
    title: '서문시장',
    regionId: 'daegu',
    category: PoiCategory.shopping,
    coordinates: Coordinates(latitude: 35.8692, longitude: 128.5817),
    shortDescription: '대구의 오래된 상권과 먹거리를 잇는 시장 POI',
  ),
  Poi(
    id: 'gwangju-acc',
    tourApiContentId: 'seed-kr-004',
    title: '국립아시아문화전당',
    regionId: 'gwangju',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1469, longitude: 126.9197),
    shortDescription: '전시와 공연 흐름을 담은 광주 문화 POI',
  ),
  Poi(
    id: 'daejeon-expo-park',
    tourApiContentId: 'seed-kr-005',
    title: '엑스포과학공원',
    regionId: 'daejeon',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 36.3742, longitude: 127.3826),
    shortDescription: '과학 도시의 전시와 산책을 연결하는 문화 POI',
  ),
  Poi(
    id: 'ulsan-taehwagang-garden',
    tourApiContentId: 'seed-kr-006',
    title: '태화강 국가정원',
    regionId: 'ulsan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.5486, longitude: 129.3019),
    shortDescription: '강변 정원 산책과 자연 보상을 연결하는 POI',
  ),
  Poi(
    id: 'sejong-lake-park',
    tourApiContentId: 'seed-kr-007',
    title: '세종호수공원',
    regionId: 'sejong',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 36.4980, longitude: 127.2747),
    shortDescription: '도심 호수와 산책 루틴을 담은 자연 POI',
  ),
  Poi(
    id: 'gyeonggi-suwon-hwaseong',
    tourApiContentId: 'seed-kr-008',
    title: '수원화성',
    regionId: 'gyeonggi',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 37.2879, longitude: 127.0165),
    shortDescription: '성곽길과 역사 미션을 연결하는 경기 POI',
  ),
  Poi(
    id: 'gangwon-seoraksan',
    tourApiContentId: 'seed-kr-009',
    title: '설악산국립공원',
    regionId: 'gangwon',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 38.1195, longitude: 128.4656),
    shortDescription: '강원 산악 경관과 자연 친밀도에 맞춘 POI',
  ),
  Poi(
    id: 'chungbuk-cheongnamdae',
    tourApiContentId: 'seed-kr-010',
    title: '청남대',
    regionId: 'chungbuk',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 36.4623, longitude: 127.4905),
    shortDescription: '호반 산책과 근현대 이야기를 담은 충북 POI',
  ),
  Poi(
    id: 'chungnam-gongsanseong',
    tourApiContentId: 'seed-kr-011',
    title: '공주 공산성',
    regionId: 'chungnam',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 36.4622, longitude: 127.1245),
    shortDescription: '백제 역사와 성곽 탐험을 잇는 충남 POI',
  ),
  Poi(
    id: 'gyeongbuk-bulguksa',
    tourApiContentId: 'seed-kr-012',
    title: '불국사',
    regionId: 'gyeongbuk',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.7900, longitude: 129.3321),
    shortDescription: '경주의 역사 상징을 담은 경북 POI',
  ),
  Poi(
    id: 'gyeongnam-haeinsa',
    tourApiContentId: 'seed-kr-013',
    title: '해인사',
    regionId: 'gyeongnam',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.8014, longitude: 128.0980),
    shortDescription: '산사와 기록문화가 만나는 경남 역사 POI',
  ),
  Poi(
    id: 'jeonbuk-hanok-village',
    tourApiContentId: 'seed-kr-014',
    title: '전주 한옥마을',
    regionId: 'jeonbuk',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.8144, longitude: 127.1536),
    shortDescription: '한옥 골목과 음식 문화를 잇는 전북 POI',
  ),
  Poi(
    id: 'jeonnam-suncheon-bay',
    tourApiContentId: 'seed-kr-015',
    title: '순천만습지',
    regionId: 'jeonnam',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 34.8850, longitude: 127.5090),
    shortDescription: '갈대밭과 생태 산책을 담은 전남 자연 POI',
  ),
  Poi(
    id: 'jeju-seongsan-ilchulbong',
    tourApiContentId: 'seed-kr-016',
    title: '성산일출봉',
    regionId: 'jeju',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 33.4580, longitude: 126.9425),
    shortDescription: '제주 오름 경관과 자연 보상을 연결하는 POI',
  ),
  Poi(
    id: 'busan-haeundae-beach',
    tourApiContentId: 'seed-001',
    title: '해운대 해수욕장',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1587, longitude: 129.1604),
    shortDescription: '부산의 바다 경험을 대표하는 자연 POI',
  ),
  Poi(
    id: 'busan-gwangalli',
    tourApiContentId: 'seed-002',
    title: '광안리 해변',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1532, longitude: 129.1187),
    shortDescription: '광안대교를 배경으로 걷는 부산 야경 코스',
  ),
  Poi(
    id: 'busan-gamcheon',
    tourApiContentId: 'seed-003',
    title: '감천문화마을',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.0975, longitude: 129.0107),
    shortDescription: '골목, 색채, 지역 이야기를 담은 문화 POI',
  ),
  Poi(
    id: 'busan-biff',
    tourApiContentId: 'seed-004',
    title: 'BIFF 광장',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.0985, longitude: 129.0286),
    shortDescription: '영화 도시 부산의 상징적인 문화 거점',
  ),
  Poi(
    id: 'busan-jagalchi',
    tourApiContentId: 'seed-005',
    title: '자갈치시장',
    regionId: 'busan',
    category: PoiCategory.food,
    coordinates: Coordinates(latitude: 35.0969, longitude: 129.0305),
    shortDescription: '부산 식문화와 시장 활기를 만나는 음식 POI',
  ),
  Poi(
    id: 'busan-gukje-market',
    tourApiContentId: 'seed-006',
    title: '국제시장',
    regionId: 'busan',
    category: PoiCategory.shopping,
    coordinates: Coordinates(latitude: 35.1016, longitude: 129.0284),
    shortDescription: '오래된 상권과 골목 탐험이 연결되는 시장 POI',
  ),
  Poi(
    id: 'busan-beomeosa',
    tourApiContentId: 'seed-007',
    title: '범어사',
    regionId: 'busan',
    category: PoiCategory.history,
    coordinates: Coordinates(latitude: 35.2836, longitude: 129.0686),
    shortDescription: '역사와 산책 동선을 함께 담은 역사 POI',
  ),
  Poi(
    id: 'busan-museum',
    tourApiContentId: 'seed-008',
    title: '부산박물관',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1282, longitude: 129.0920),
    shortDescription: '부산의 역사와 문화를 학습하는 문화시설',
  ),
  Poi(
    id: 'busan-cinema-center',
    tourApiContentId: 'seed-009',
    title: '영화의전당',
    regionId: 'busan',
    category: PoiCategory.culture,
    coordinates: Coordinates(latitude: 35.1710, longitude: 129.1270),
    shortDescription: '영화제와 지역 문화 이벤트의 중심지',
  ),
  Poi(
    id: 'busan-fireworks',
    tourApiContentId: 'seed-010',
    title: '부산불꽃축제',
    regionId: 'busan',
    category: PoiCategory.festival,
    coordinates: Coordinates(latitude: 35.1532, longitude: 129.1187),
    shortDescription: '기분 지표 보상에 특화된 축제 POI',
  ),
  Poi(
    id: 'busan-spa-land',
    tourApiContentId: 'seed-011',
    title: '해운대 온천권',
    regionId: 'busan',
    category: PoiCategory.other,
    coordinates: Coordinates(latitude: 35.1632, longitude: 129.1636),
    shortDescription: '휴식과 회복 콘셉트의 기타 POI',
  ),
  Poi(
    id: 'busan-dongbaek',
    tourApiContentId: 'seed-012',
    title: '동백섬',
    regionId: 'busan',
    category: PoiCategory.nature,
    coordinates: Coordinates(latitude: 35.1527, longitude: 129.1522),
    shortDescription: '해안 산책과 재방문 친밀도에 적합한 자연 POI',
  ),
];

const starterPetTemplates = <PetTemplate>[
  PetTemplate(
    id: 'wave-naru',
    name: '파도나루',
    regionId: 'korea',
    rarity: 'common',
    primaryCategory: PoiCategory.nature,
    basePersonality: '바다 산책을 좋아하고 새로운 길을 먼저 살핀다.',
    colorValue: 0xFF0EA5E9,
    initials: 'PN',
    assetKey: 'red_scarf_dori',
  ),
  PetTemplate(
    id: 'harbor-maru',
    name: '항구마루',
    regionId: 'korea',
    rarity: 'common',
    primaryCategory: PoiCategory.food,
    basePersonality: '시장과 골목의 소리에 민감하고 먹거리 이야기에 밝다.',
    colorValue: 0xFFF97316,
    initials: 'HM',
    assetKey: 'bandana_tanuki',
  ),
  PetTemplate(
    id: 'film-bori',
    name: '필름보리',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.culture,
    basePersonality: '장면과 대사를 기억하며 문화 공간에서 활발해진다.',
    colorValue: 0xFF7C3AED,
    initials: 'FB',
    assetKey: 'wink_yellow_pup',
  ),
  PetTemplate(
    id: 'spark-yuri',
    name: '불꽃유리',
    regionId: 'korea',
    rarity: 'epic',
    primaryCategory: PoiCategory.festival,
    basePersonality: '사람들이 모이는 순간의 빛과 소리를 좋아한다.',
    colorValue: 0xFFDB2777,
    initials: 'BY',
    assetKey: 'roof_mascot_pipeline_256',
  ),
  PetTemplate(
    id: 'spring-dami',
    name: '온천다미',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.other,
    basePersonality: '차분하고 회복을 좋아하며 긴 산책 뒤에 힘을 낸다.',
    colorValue: 0xFF14B8A6,
    initials: 'OD',
    assetKey: 'flower_mint_buddy',
  ),
  PetTemplate(
    id: 'story-goun',
    name: '설화고운',
    regionId: 'korea',
    rarity: 'epic',
    primaryCategory: PoiCategory.history,
    basePersonality: '오래된 장소의 이름과 이야기를 차근차근 알려준다.',
    colorValue: 0xFF8B5CF6,
    initials: 'SG',
    assetKey: 'autumn_leaf_sprite',
  ),
  PetTemplate(
    id: 'alley-raon',
    name: '골목라온',
    regionId: 'korea',
    rarity: 'rare',
    primaryCategory: PoiCategory.shopping,
    basePersonality: '간판, 상점, 골목의 작은 발견을 빠르게 기억한다.',
    colorValue: 0xFFB45309,
    initials: 'GR',
    assetKey: 'roof_mascot_pipeline_128',
  ),
];

const starterDialogueSeed = <DialogueLine>[
  DialogueLine(
    id: 'wave-naru-default',
    templateId: 'wave-naru',
    trigger: 'default',
    text: '오늘 바람은 새로운 지역에서 불어와. 가까운 산책길부터 살펴보자.',
  ),
  DialogueLine(
    id: 'wave-naru-nature',
    templateId: 'wave-naru',
    trigger: 'nature',
    text: '자연 가까이를 걸으니 몸이 가벼워졌어. 다음 산책길도 찾아보자.',
  ),
  DialogueLine(
    id: 'wave-naru-food',
    templateId: 'wave-naru',
    trigger: 'food',
    text: '시장 골목을 지나면 파도 소리와 다른 활기가 느껴져. 오늘 기분이 든든해.',
  ),
  DialogueLine(
    id: 'wave-naru-festival',
    templateId: 'wave-naru',
    trigger: 'festival',
    text: '축제 불빛이 물결처럼 번졌어. 지역의 밤길은 걸을수록 반짝인다.',
  ),
  DialogueLine(
    id: 'wave-naru-culture',
    templateId: 'wave-naru',
    trigger: 'culture',
    text: '문화 공간을 지나오니 길의 표정이 달라졌어. 오늘 본 장면을 기억해둘게.',
  ),
  DialogueLine(
    id: 'wave-naru-history',
    templateId: 'wave-naru',
    trigger: 'history',
    text: '오래된 길에도 바람길이 있구나. 조용히 걸으니 지역의 시간이 들려.',
  ),
  DialogueLine(
    id: 'wave-naru-shopping',
    templateId: 'wave-naru',
    trigger: 'shopping',
    text: '상점 사이를 지나니 발걸음이 빨라졌어. 다음 골목도 함께 살펴보자.',
  ),
  DialogueLine(
    id: 'wave-naru-other',
    templateId: 'wave-naru',
    trigger: 'other',
    text: '잠깐 쉬어가는 길도 산책의 일부야. 숨을 고르고 다시 움직여보자.',
  ),
  DialogueLine(
    id: 'harbor-maru-default',
    templateId: 'harbor-maru',
    trigger: 'default',
    text: '시장 냄새가 나는 길은 그냥 지나치기 어렵지. 오늘도 한 바퀴 돌아보자.',
  ),
  DialogueLine(
    id: 'harbor-maru-nature',
    templateId: 'harbor-maru',
    trigger: 'nature',
    text: '바다 바람을 맡으니 배가 더 고파졌어. 산책 뒤에는 따뜻한 간식이 좋겠다.',
  ),
  DialogueLine(
    id: 'harbor-maru-food',
    templateId: 'harbor-maru',
    trigger: 'food',
    text: '시장 쪽은 늘 활기가 있어. 기분이 확 올라간다.',
  ),
  DialogueLine(
    id: 'harbor-maru-festival',
    templateId: 'harbor-maru',
    trigger: 'festival',
    text: '축제 길에는 먹거리 냄새도 같이 따라와. 오늘은 기분 보상이 넉넉하겠어.',
  ),
  DialogueLine(
    id: 'harbor-maru-culture',
    templateId: 'harbor-maru',
    trigger: 'culture',
    text: '영화와 전시 이야기를 들으니 시장 소리도 장면처럼 들려. 꽤 멋진 하루야.',
  ),
  DialogueLine(
    id: 'harbor-maru-history',
    templateId: 'harbor-maru',
    trigger: 'history',
    text: '오래된 장소 근처엔 오래된 가게도 많지. 오늘 기억은 천천히 익어갈 거야.',
  ),
  DialogueLine(
    id: 'harbor-maru-shopping',
    templateId: 'harbor-maru',
    trigger: 'shopping',
    text: '오래된 상권의 골목은 발걸음마다 이야기가 달라져. 잘 따라와.',
  ),
  DialogueLine(
    id: 'harbor-maru-other',
    templateId: 'harbor-maru',
    trigger: 'other',
    text: '온천권처럼 쉬어가는 곳도 필요해. 기분을 데우고 다시 움직이자.',
  ),
  DialogueLine(
    id: 'film-bori-default',
    templateId: 'film-bori',
    trigger: 'default',
    text: '지역의 길은 장면처럼 이어져. 오늘은 어떤 장소를 기록할까?',
  ),
  DialogueLine(
    id: 'film-bori-nature',
    templateId: 'film-bori',
    trigger: 'nature',
    text: '해변의 빛은 매번 다른 컷 같아. 오늘 장면은 오래 남을 거야.',
  ),
  DialogueLine(
    id: 'film-bori-food',
    templateId: 'film-bori',
    trigger: 'food',
    text: '시장 장면은 대사가 많아. 사람들 목소리까지 기록하고 싶어졌어.',
  ),
  DialogueLine(
    id: 'film-bori-festival',
    templateId: 'film-bori',
    trigger: 'festival',
    text: '축제는 클라이맥스 같아. 음악과 불빛이 한 번에 지나갔어.',
  ),
  DialogueLine(
    id: 'film-bori-culture',
    templateId: 'film-bori',
    trigger: 'culture',
    text: '문화 공간을 다녀오니 기억할 장면이 늘었어. 지식도 조금 자란 것 같아.',
  ),
  DialogueLine(
    id: 'film-bori-history',
    templateId: 'film-bori',
    trigger: 'history',
    text: '역사 장소는 긴 다큐멘터리 같아. 천천히 보면 놓친 장면이 보여.',
  ),
  DialogueLine(
    id: 'film-bori-shopping',
    templateId: 'film-bori',
    trigger: 'shopping',
    text: '상점 간판들이 화면 전환처럼 이어졌어. 다음 컷도 기대된다.',
  ),
  DialogueLine(
    id: 'film-bori-other',
    templateId: 'film-bori',
    trigger: 'other',
    text: '쉬어가는 장면이 있어야 다음 장면이 더 선명해져. 잠깐 호흡을 맞추자.',
  ),
  DialogueLine(
    id: 'spark-yuri-default',
    templateId: 'spark-yuri',
    trigger: 'default',
    text: '오늘 불빛이 모이는 쪽으로 걸어가 보자. 사람들의 웃음이 길을 밝혀줄 거야.',
  ),
  DialogueLine(
    id: 'spark-yuri-nature',
    templateId: 'spark-yuri',
    trigger: 'nature',
    text: '풀빛 사이에도 작은 무대가 숨어 있어. 조용한 박수처럼 바람이 지나가.',
  ),
  DialogueLine(
    id: 'spark-yuri-food',
    templateId: 'spark-yuri',
    trigger: 'food',
    text: '따뜻한 냄새가 불꽃처럼 올라와. 먹거리 골목은 늘 축제의 시작이야.',
  ),
  DialogueLine(
    id: 'spark-yuri-festival',
    templateId: 'spark-yuri',
    trigger: 'festival',
    text: '축제 한가운데에 서니 마음이 반짝거려. 오늘 기분 보상은 충분해.',
  ),
  DialogueLine(
    id: 'spark-yuri-culture',
    templateId: 'spark-yuri',
    trigger: 'culture',
    text: '공연장 밖의 발걸음까지 하나의 장면 같아. 이 기억은 오래 빛날 거야.',
  ),
  DialogueLine(
    id: 'spark-yuri-history',
    templateId: 'spark-yuri',
    trigger: 'history',
    text: '오래된 장소에도 축제의 흔적이 남아 있어. 이름을 따라 천천히 걸어보자.',
  ),
  DialogueLine(
    id: 'spark-yuri-shopping',
    templateId: 'spark-yuri',
    trigger: 'shopping',
    text: '상점 불빛이 줄지어 켜졌어. 골목 전체가 작은 퍼레이드 같아.',
  ),
  DialogueLine(
    id: 'spark-yuri-other',
    templateId: 'spark-yuri',
    trigger: 'other',
    text: '잠깐 쉬어도 괜찮아. 다음 불빛을 보기 전엔 숨을 고르는 시간이 필요해.',
  ),
  DialogueLine(
    id: 'alley-raon-default',
    templateId: 'alley-raon',
    trigger: 'default',
    text: '골목은 자세히 보면 작은 보물지도가 돼. 오늘은 간판 사이를 천천히 읽어보자.',
  ),
  DialogueLine(
    id: 'alley-raon-nature',
    templateId: 'alley-raon',
    trigger: 'nature',
    text: '바깥 바람을 쐬고 오니 골목 소리도 더 선명해졌어. 좋은 균형이야.',
  ),
  DialogueLine(
    id: 'alley-raon-food',
    templateId: 'alley-raon',
    trigger: 'food',
    text: '맛있는 냄새를 따라가면 지역의 하루가 보여. 기분이 든든하게 찼어.',
  ),
  DialogueLine(
    id: 'alley-raon-festival',
    templateId: 'alley-raon',
    trigger: 'festival',
    text: '축제 날의 골목은 한층 바빠져. 사람들 흐름을 따라가면 새 길이 열려.',
  ),
  DialogueLine(
    id: 'alley-raon-culture',
    templateId: 'alley-raon',
    trigger: 'culture',
    text: '전시와 상점은 닮은 점이 있어. 만든 사람의 취향이 길에 남거든.',
  ),
  DialogueLine(
    id: 'alley-raon-history',
    templateId: 'alley-raon',
    trigger: 'history',
    text: '오래된 상권에는 시간의 층이 쌓여 있어. 간판 하나도 기록처럼 보여.',
  ),
  DialogueLine(
    id: 'alley-raon-shopping',
    templateId: 'alley-raon',
    trigger: 'shopping',
    text: '오늘은 제대로 찾았어. 상점 사이를 걸을수록 지역 친밀도가 올라가.',
  ),
  DialogueLine(
    id: 'alley-raon-other',
    templateId: 'alley-raon',
    trigger: 'other',
    text: '쉬어가는 자리도 좋은 발견이야. 다음 골목을 볼 힘을 아껴두자.',
  ),
  DialogueLine(
    id: 'spring-dami-default',
    templateId: 'spring-dami',
    trigger: 'default',
    text: '천천히 걸어도 괜찮아. 오래 머무는 만큼 이 지역과 가까워질 수 있어.',
  ),
  DialogueLine(
    id: 'spring-dami-nature',
    templateId: 'spring-dami',
    trigger: 'nature',
    text: '바닷바람이 기분을 씻어주는 것 같아. 오늘 산책은 몸에 잘 맞아.',
  ),
  DialogueLine(
    id: 'spring-dami-food',
    templateId: 'spring-dami',
    trigger: 'food',
    text: '따뜻한 음식 냄새가 지나가니 마음이 놓여. 천천히 에너지를 채우자.',
  ),
  DialogueLine(
    id: 'spring-dami-festival',
    templateId: 'spring-dami',
    trigger: 'festival',
    text: '축제 길은 조금 북적이지만 괜찮아. 즐거운 소리가 기분을 올려줘.',
  ),
  DialogueLine(
    id: 'spring-dami-culture',
    templateId: 'spring-dami',
    trigger: 'culture',
    text: '전시와 공연 이야기는 마음을 차분하게 해. 오늘 배운 걸 오래 간직하자.',
  ),
  DialogueLine(
    id: 'spring-dami-history',
    templateId: 'spring-dami',
    trigger: 'history',
    text: '오래된 장소는 천천히 봐야 해. 숨을 고르면 더 많은 이야기가 보여.',
  ),
  DialogueLine(
    id: 'spring-dami-shopping',
    templateId: 'spring-dami',
    trigger: 'shopping',
    text: '골목을 둘러보는 속도도 우리답게 맞추면 돼. 필요한 만큼만 걸어보자.',
  ),
  DialogueLine(
    id: 'spring-dami-other',
    templateId: 'spring-dami',
    trigger: 'other',
    text: '휴식 장소를 찾은 건 좋은 선택이야. 회복도 탐험의 중요한 보상이니까.',
  ),
  DialogueLine(
    id: 'story-goun-default',
    templateId: 'story-goun',
    trigger: 'default',
    text: '오래된 이름에는 이유가 있어. 오늘 방문한 곳의 이야기도 찾아보자.',
  ),
  DialogueLine(
    id: 'story-goun-nature',
    templateId: 'story-goun',
    trigger: 'nature',
    text: '해안길의 이름에도 오래된 기억이 숨어 있어. 바람이 먼저 알려주네.',
  ),
  DialogueLine(
    id: 'story-goun-food',
    templateId: 'story-goun',
    trigger: 'food',
    text: '시장 음식은 사람들의 생활사를 품고 있어. 한 입의 이야기도 가볍지 않아.',
  ),
  DialogueLine(
    id: 'story-goun-festival',
    templateId: 'story-goun',
    trigger: 'festival',
    text: '축제는 도시가 기억을 함께 나누는 방식이야. 오늘의 소리도 기록해두자.',
  ),
  DialogueLine(
    id: 'story-goun-culture',
    templateId: 'story-goun',
    trigger: 'culture',
    text: '문화 공간에는 지금의 지역이 남기는 문장이 있어. 지식이 또 깊어졌어.',
  ),
  DialogueLine(
    id: 'story-goun-history',
    templateId: 'story-goun',
    trigger: 'history',
    text: '역사 명소를 걸으면 기억이 깊어진다. 내 지식도 함께 자랐어.',
  ),
  DialogueLine(
    id: 'story-goun-shopping',
    templateId: 'story-goun',
    trigger: 'shopping',
    text: '오래된 상권은 도시의 생활 기록이야. 간판 하나도 허투루 보이지 않아.',
  ),
  DialogueLine(
    id: 'story-goun-other',
    templateId: 'story-goun',
    trigger: 'other',
    text: '쉬어가는 장소에도 이름의 이유가 있어. 잠시 멈춰서 들어보자.',
  ),
];
